Review Request
MykhailoRomanenko/gpt-summarizer-rs pull request #1
Opened 2023-10-07 08:52 UTC by MykhailoRomanenko

2023-10-07 10:44 UTC, Amex1048 requested changes

2023-10-07 10:44 UTC, Amex1048 commented on src/lib.rs
> +        .select(&Selector::parse("p").unwrap())
Not a frontend developer, it is not a fix, rather a question: should one include `<header>`  into an input data. Headers are summaries themselves, they might be useful?

2023-10-07 10:44 UTC, Amex1048 commented on src/lib.rs
> +    let sentence_count = 50;
Move this one into a const, maybe? Or config?

2023-10-07 10:44 UTC, Amex1048 commented on src/extractive_summary.rs
> +    let damping_factor = 0.85;
Consts, maybe?

2023-10-07 11:14 UTC, MykhailoRomanenko commented on src/extractive_summary.rs
> +    let damping_factor = 0.85;
This is a common heuristically derived value that does not need to be changed

2023-10-07 11:38 UTC, Jujumba commented on src/lib.rs
> +            other => output.push(other),
Instead of destructing and constructing the same object, you can do the following:
```rust
match chunk {
  response @ ResponseChunk::Content { .. } => {
    print!("{:?}", response);
    // rest of the code
    output.push(response);
  }
  _ => // rest of the code
}
```
[More ](https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#-bindings)on this

2023-10-07 11:38 UTC, Jujumba commented on src/lib.rs
> +        if children_text.len() > 0 {
You can use `String::is_empty()` here

2023-10-07 13:38 UTC, MykhailoRomanenko commented on src/lib.rs
> +            other => output.push(other),
Thank you very much! Didn't know that

2023-10-07 13:53 UTC, MykhailoRomanenko commented on src/lib.rs
> +        .select(&Selector::parse("p").unwrap())
Headers are usually for controls and navigation and are not relevant to the content.

2023-10-07 14:21 UTC, MykhailoRomanenko commented on src/lib.rs
> +            other => output.push(other),
However, I came with a more succinct variant

2023-10-07 14:21 UTC, MykhailoRomanenko commented on src/lib.rs
> +    let sentence_count = 50;
Done

2023-10-07 14:21 UTC, MykhailoRomanenko commented on src/lib.rs
> +        if children_text.len() > 0 {
Done

2023-10-07 14:32 UTC, Amex1048 approved these changes

2023-10-07 16:12 UTC, Jujumba approved these changes

2023-10-07 18:20 UTC, TheBestTvarynka approved these changes

2023-10-07 19:29 UTC, WizardPlatypus commented on src/extractive_summary.rs
> +        prev_result = result.clone();
You've done a great job, there's basically nothing to review. But I shall leave this tiny note.

At the end of each iteration, there are 2 duplicates of `result`'s data. But at the beginning of next iteration, one of the duplicates is dropped. Basically, you are perfoming unnecessary cloning.

Here is a simple fix.
At the beginning of the iteration, _move_ data from `result` to `prev_result`. Then, calculate the new value, `result = initial_m.dot(&prev_result);`. Then do the rest - no extra cloning needed. This way you also don't need to bring `prev_result` to the outer scope.

```rust
// inside the loop
let prev_result = result; // move instead of clone
result = initial_m.dot(&prev_result);
let delta = &result - &prev_result;
// ...
```

Memory optimization ho-ray!

2023-10-07 19:33 UTC, WizardPlatypus requested changes

2023-10-07 19:33 UTC, WizardPlatypus commented on src/extractive_summary.rs
> +        prev_result = result.clone();
You've done a great job, there's basically nothing to review. But I shall leave this tiny note.

At the end of each iteration, there are 2 duplicates of `result`'s data. But at the beginning of next iteration, one of the duplicates is dropped. Basically, you are perfoming unnecessary cloning.

Here is a simple fix.
At the beginning of the iteration, _move_ data from `result` to `prev_result`. Then, calculate the new value, `result = initial_m.dot(&prev_result);`. Then do the rest - no extra cloning needed. This way you also don't need to bring `prev_result` to the outer scope.

```rust
// inside the loop
let prev_result = result; // move instead of clone
result = initial_m.dot(&prev_result);
let delta = &result - &prev_result;
// ...
```

Memory optimization ho-ray!

2023-10-07 19:40 UTC, MykhailoRomanenko commented on src/extractive_summary.rs
> +        prev_result = result.clone();
Thank you very much, very clever! Fixed

2023-10-07 19:41 UTC, WizardPlatypus approved these changes

2023-10-07 19:42 UTC, WizardPlatypus commented on src/extractive_summary.rs
> +        prev_result = result.clone();
Happy to help!

2023-10-07 19:43 UTC, WizardPlatypus approved these changes

2023-10-07 19:54 UTC, shurikv requested changes

2023-10-07 19:54 UTC, shurikv commented on src/lib.rs
> +            print!("{delta}");
I think that you forgot remove print!. If not - use logger instead

2023-10-08 17:22 UTC, MykhailoRomanenko commented on src/config.rs
> +        config.try_deserialize().unwrap()
Fixed

2023-10-08 17:22 UTC, MykhailoRomanenko commented on Cargo.toml
> +dotenv = "0.15.0"
Fixed

2023-10-08 17:22 UTC, MykhailoRomanenko commented on src/lib.rs
> +            print!("{delta}");
This print! is totally deliberate

2023-10-08 17:23 UTC, MykhailoRomanenko commented
Thanks everyone for the insightful reviews!

2023-10-08 17:23 UTC, merged